#import "main/com/photon/phresco/util/MainActivity.js"
#import "main/com/photon/phresco/util/UIElements.js"
#import "test/com/photon/phresco/testcase/Registration_Testsuite.js"
#import "test/com/photon/phresco/testcase/Login_TestSuite.js"
#import "test/com/photon/phresco/testcase/Mycart_TestSuite.js"
